name: Code Spell Check
on: [pull_request]

jobs:
  code-spell-check:
    name: Spell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm i --color
      - name: Run Spell Check
        shell: bash
        run: npx cspell "**" --gitignore
