name: Unit Tests
on:
  pull_request:
    branches:
      - main

jobs:
  cargo-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-check

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo check
        run: cargo check --color always --all --all-targets
  cargo-test:
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        with:
          profile: minimal
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-test-release-${{ matrix.os }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.0
    
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i --color --frozen-lockfile

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo test
        run: cargo test --release --tests
